.gitignore, .goreleaser.yml, Dockerfile
Signed-off-by: Carlos A Becker <caarlos0@gmail.com>
=> fix: clean up GoReleaser config

README.md
=> Fix releases link in README

go.mod
Clean up the require groups manually.
=> Tidy up go.mod

cmd/soft/main.go, config/config.go, internal/config/config.go, internal/config/git.go, internal/git/git.go, internal/tui/style/style.go, server/server.go
This update adds missing GoDocs to all parts of the application except those related to Bubble Tea.
=> Add some missing GoDocs

config/config.go
=> Fix bug where ssh key cannot be written on Windows

.github/workflows/goreleaser-publish.yml, .goreleaser.yml, go.mod, go.sum
also ignore windows arm64 and arm7 builds
needs: charmbracelet/bubbletea#167
=> Add separate goreleaser test workflow and add freebsd

cmd/soft/main.go, server/server.go
=> fix: graceful shutdown

README.md
=> docs: readme about RSA SHA2 keys

internal/tui/bubbles/repo/bubble.go
Credit to @aymanbagabas for the fix.
=> fix: chroma portions of glamour renders that could break layout

cmd/soft/main.go, config/config.go, internal/config/config.go, server/server.go
=> fix: rename host to bind address

internal/git/git.go, internal/tui/bubble.go, internal/tui/bubbles/git/bubble.go, internal/tui/bubbles/git/log/bubble.go, internal/tui/bubbles/git/tree/bubble.go, internal/tui/bubbles/git/types/git.go, internal/tui/bubbles/selection/bubble.go
* Cache repository trees 
* Cache repository commits
* Refactor names and fix lint warnings
=> Cache git trees and commits

internal/config/config.go, internal/config/git.go, internal/tui/bubbles/git/bubble.go, internal/tui/bubbles/git/log/bubble.go, internal/tui/bubbles/git/refs/bubble.go, internal/tui/bubbles/git/tree/bubble.go, internal/tui/bubbles/repo/bubble.go, internal/tui/commands.go
* Lazy load git tui bubbles
* Don't block on git push reload
=> Lazy load git tui bubbles

config/config.go, internal/config/config.go, internal/git/git.go, internal/tui/bubbles/git/refs/bubble.go, server/middleware.go
* Only show branches and tags in the branches bubble
* List directory entries when path is a directory
=> TUI: only show branches and tags, cat mw: list directory entries

.gitignore, server/middleware.go, server/middleware_test.go, server/server.go, server/server_test.go
=> [WIP] add tests

git/errors.go, git/repo.go, internal/git/git.go
Fixes: https://github.com/charmbracelet/soft-serve/issues/108
=> fix: don't load non-git repos

tui/log/bubble.go
Show a delayed spinner when loading commits
=> feat: show spinner when loading commits

README.md
=> docs: add how to manage and delete repos

go.mod, go.sum, internal/tui/commands.go, server/middleware.go
only display private repos for users with read access, anon users won't have access to private repos.
Fixes: https://github.com/charmbracelet/soft-serve/issues/81
=> fix: respect private repos

.gitignore, .goreleaser.yml, scripts/completions.sh, scripts/manpages.sh
using mango-cobra
Needs: https://github.com/charmbracelet/meta/pull/33
=> feat: generate man pages and completions

README.md
=> Fix example commands

README.md
Fixes same issue as Gum issue #23
=> Fixes #133

config/auth.go, server/server.go
no need to enter a password for keyless users
=> feat(server): use keyboard-interactive auth instead of password

ui/pages/repo/repo.go, ui/pages/selection/selection.go, ui/styles/styles.go, ui/ui.go
Fixes: https://github.com/charmbracelet/soft-serve/issues/172
=> fix: hide tabs while filtering

ui/keymap/keymap.go, ui/pages/repo/files.go, ui/pages/repo/log.go, ui/pages/repo/refs.go, ui/pages/repo/repo.go, ui/pages/selection/selection.go, ui/styles/styles.go, ui/ui.go
- Fix incorrect help while filtering
- Support right mouse click to go back
- Support backspace key to go back
Fixes: https://github.com/charmbracelet/soft-serve/issues/138
=> UI Improvements

server/server_test.go, server/session.go, server/session_test.go
Prevent unauthorized ui access to private repos.
Fixes: https://github.com/charmbracelet/soft-serve/issues/189
=> fix(session): unauthorized access to private repos

.github/workflows/build.yml
=> feat(ci): add code coverage

git/repo.go, server/backend/access.go, server/backend/backend.go, server/backend/file/file.go, server/backend/file/repo.go, server/backend/repo.go, server/backend/utils.go
Add file backend that uses filesystem to manage non-git operations.
A backend manages git repositories and handles non-git related operations like repository description, collaborators, etc.
=> feat(backend): server backend

.nfpm/postinstall.sh, .nfpm/postremove.sh
Add systemd service, sysuser, and tmpfiles but _don't_ enable and start service.
=> fix(nfpm): don't enable and start systemd service by default

Dockerfile
=> #264 - Add OpenSSH to Docker image

internal/sync/workqueue.go, server/jobs.go
Use semaphores to implement a workpool of n workers
and use that to run the mirroring job
=> feat(wp): use a workpool impl

server/ssh/ssh.go
only accept readwrite access using pubkey auth. Keyboard-interactive auth will be used after all keys authentication has failed
this fixes the issue of authenticating "too many authentications"
=> fix(ssh): restrict publickey auth

git/repo.go, testscript/testdata/repo-tree.txtar
removed function was not being used anywhere
=> test: repo tree tests

testscript/script_test.go, testscript/testdata/help.txtar, testscript/testdata/repo-blob.txtar, testscript/testdata/repo-create.txtar, testscript/testdata/repo-delete.txtar, testscript/testdata/repo-tree.txtar, testscript/testdata/settings.txtar
- --help
- repo blob
- more settings
=> test: more cmd tests

testscript/script_test.go, testscript/testdata/repo-create.txtar, testscript/testdata/repo-perms.txtar
fwiw:
- `soft` is `admin` soft-serve over SSH
- `usoft` is `user1` soft-serve over SSH
=> test: collab tests

server/config/file.go, server/hooks/gen.go
Convert slashes on windows
Fixes: https://github.com/charmbracelet/soft-serve/issues/367
=> fix: config paths on windows

.github/workflows/build.yml, cmd/soft/root.go, server/db/db.go, server/store/database/access_token.go, server/store/database/collab.go, server/store/database/settings.go, server/store/database/user.go, testscript/script_test.go
- Fix Postgres timezone token issue (pq returns date based on local timezone, this means we have to store date types in UTC)
- Add Postgres testscript
- Run CI tests for both sqlite and postgres
=> Fix Postgres related issues and add CI

testscript/testdata/mirror.txtar, testscript/testdata/repo-collab.txtar, testscript/testdata/repo-import.txtar, testscript/testdata/soft-browse.txtar
wizard tutorial last commit was 2y ago
catwalk get commits almost daily
=> test: use a repo that doesn't change as much
