README.md, main.go
Version & SHA are being set via go build's ldflags.
=> Add --help and --version flags

internal/tui/bubbles/repo/bubble.go, internal/tui/style/style.go
This update addresses basic readability issues on light backgrounds.
While it's sufficient for most cases, there are a few colors with respect to source code that can be improved. Those should be handled upstream in a new [Glamour](https://github.com/charmbracelet/glamour) stylesheet.
Fixes #37.
=> Add basic support for light backgrounds

server/server.go
Note that precedence will be given to the environment variables.
Fixes #38.
=> Honor the host and port settings in the YAML config

README.md, internal/config/defaults.go, server/server.go
=> Clarify that host 'n port settings in config are for display purposes

.goreleaser.yml
This tiny update updates the image in the footer added to releases by `goreleaser`.
=> Update footer image in release template

README.md, internal/config/defaults.go
closes #63
`KEY TEXT` is indeed a bit confusing, had the same questions on wishlist... maybe improving the placeholder helps?
=> fix: improve key examples

README.md
=> docs: improve docs about keyless auth

internal/config/config.go
- try to read it, in case its a file
- try to parse the key right away and fail early, instead of logging `error: malformed authorized key: 'yadayada'` when users try to ssh/clone later on
refs #55
=> feat: improve handling of SOFT_SERVE_INITIAL_ADMIN_KEY

go.sum, server/middleware.go, server/server.go
sshing with a filepath in a non-interactive terminal spits out the file
content with the option of syntax highlighting and line numbers
example:
```sh
$ ssh git.charm.sh soft-serve/server/server.go # no syntax highlighting
$ ssh git.charm.sh soft-serve/server/server.go formatting # with syntax highlighting
$ ssh git.charm.sh soft-serve/server/server.go lineno # with line numbers
$ ssh git.charm.sh soft-serve/server/server.go lineno formatting # with line numbers and syntax highlighting
```
=> feat: display files middleware

internal/tui/bubble.go, internal/tui/bubbles/git/about/bubble.go, internal/tui/bubbles/git/bubble.go, internal/tui/bubbles/git/log/bubble.go, internal/tui/bubbles/git/refs/bubble.go, internal/tui/bubbles/git/tree/bubble.go, internal/tui/bubbles/git/types/formatter.go, internal/tui/bubbles/git/types/help.go
* Use glamour to render markdown files otherwise default to chroma
* Fix error when switching refs
* Change git tui navigation keys to R readme, F files, B branches, and C commits
=> Use glamour to render markdown files and fix error when switching refs

server/middleware.go
This PR:
* Adds coloring to line-numbering when color is specified. Colors will work on both light and dark backgrounds
* Line numbers are now padded on the left
=> chore: line number coloring

go.mod, go.sum, internal/git/git.go, internal/tui/bubbles/git/about/bubble.go, internal/tui/bubbles/git/bubble.go, internal/tui/bubbles/git/log/bubble.go, internal/tui/bubbles/git/refs/bubble.go, internal/tui/bubbles/git/tree/bubble.go, internal/tui/bubbles/git/types/git.go, internal/tui/style/style.go
* Add commit loading spinner
* Add pagination indicators
* Fix resizing window not reflecting on tui
* Fix selecting a file in a empty list
* Show message on empty list and empty readme
~Waiting on: https://github.com/charmbracelet/bubbles/pull/123~
=> Git TUI improvements

README.md, go.mod, go.sum, internal/config/config.go, internal/config/defaults.go, internal/config/git.go, internal/git/git.go, internal/tui/bubbles/git/about/bubble.go, internal/tui/bubbles/git/tree/bubble.go, internal/tui/bubbles/git/types/formatter.go, internal/tui/bubbles/git/types/git.go, internal/tui/commands.go
* Optionally specify per repo readme file path in config
* Default to "README*" glob and choose the first glob match
* Refactor code and move stuff around
* UpdateServerInfo on repo push
=> Custom readme path

examples/non-root/main.go, examples/setuid/main.go, internal/config/config.go, internal/config/defaults.go, internal/git/git.go, server/server.go
* Fix default config repo first commit time
* Fix allowing keyless when no pk provided
* Expose ssh server `Serve()` to listen on a custom net.Listener
* Add running soft-serve as a non root on port 22 example
Closes: https://github.com/charmbracelet/soft-serve/issues/116
EDIT: to test this out `go build ./examples/setuid && sudo ./setuid`
=> Run soft-serve as non-root on port 22

README.md
This PR fixes the GIF rendering on small mobile screens and makes the GIF 100%
of the width unless the screen is larger than 750px in which case the GIF is
set to 750px as the max-width.
=> Fix GIF on mobile

README.md, config/defaults.go
Private repos can be accessed by admins and collab users. All other users can read public repos based on the anon-access setting.
Fixes: https://github.com/charmbracelet/soft-serve/issues/165
=> fix: misleading authorized users comment

README.md
I believe this was meant by the `reverse proxy` wording. But I believe this wording is confusing because it means something specific for http proxying
=> Improve port forwarding wording

server/config/config.go, server/http.go, server/server.go
With this, soft-serve will be able to serve Go modules as well!
An simple PoC would be:
```sh
SOFT_SERVE_HTTP_DOMAIN=mydomain.com go run ./cmd/soft serve
sudo ./caddy reverse-proxy --from mydomain.com --to localhost:8080
```
and then you can push your repo (with import-path being something like `mydomain.com/name`) and `go get` it with:
```sh
GOPRIVATE=mydomain.com/name go get mydomain.com/name
```
PS: it only works with default ports (80 and 443), and the https port needs to have a valid certificate (hence using caddy autotls stuff in the example above).
Let me know what you think!
=> feat: serve index.html for go modules

go.mod
`go install` doesn't like `exclude/replace` directives in go.mod
Fixes: https://github.com/charmbracelet/soft-serve/issues/213
Fixes: https://github.com/charmbracelet/soft-serve/issues/201
=> fix(go): remove go.mod exclude directives

config/git.go
Skip loading repos with broken head ref.
Fixes: https://github.com/charmbracelet/soft-serve/issues/235
=> fix(config): ignore repos with broken head ref

cmd/soft/root.go, server/config/config.go, server/config/file.go
~~I particularly want to also see the time... not sure if this should be the default, or if we should make this customizable. In this pr I'm just changing the default.~~
Allows to customize the log time format.
=> feat: log time format

git/repo.go, server/backend/sqlite/sqlite.go
- increase clone timeout from 1m to 15m
- otherwise, bigger repos might just fail to import
- removed some unused functions
- cleaned up a couple of lint issues
=> fix: increase clone timeout, fix some lint issues

go.mod, go.sum, server/backend/backend.go, server/backend/context.go, server/backend/sqlite/sqlite.go, server/cmd/cmd.go, server/daemon/daemon.go, server/daemon/daemon_test.go, server/server.go, server/ssh/ssh.go, server/web/http.go
Use the connection context when running external commands.
Remove go.mod replace once https://github.com/gogs/git-module/pull/95 is merged
=> fix(server): bound the current context to the underlying operation

Dockerfile
copies the binary and installs packages in the end, so previous layers can be reused.
=> fix: improve dockerfile caching

cmd/soft/root.go, go.mod, go.sum, internal/sync/workqueue.go, server/jobs.go, server/server.go
Implement a simple chunked workqueue to queue updating mirrors. We use the number of cpus to calculate the number of workers to distribute the work to.
=> perf: update mirrors in a workpool

Dockerfile
if you run soft-serve in a docker container with `--tty` (default in synology nas, and I imagine, probably in other Docker UIs too), every bg/fg query will timeout (after 5s), so, it has a 10s delay to start (because it checks both bg and fg on startup), and then SSH-ing into the TUI is impossible as it keeps doing queries nonstop.
This is a workaround to prevent this issue until we finish working on a proper fix.
=> fix: set CI=1 in Dockerfile as a workaround

server/backend/sqlite/hooks.go, server/backend/sqlite/sqlite.go
when i/o errors, transaction rolls back
=> fix(backend): wrap i/o operations in transactions

cmd/soft/root.go, git/repo.go, internal/log/log.go, server/backend/sqlite/hooks.go, server/backend/sqlite/sqlite.go, server/git/git.go, server/ssh/session.go, server/ui/components/code/code.go, server/ui/components/viewport/viewport.go, server/ui/pages/repo/log.go, server/ui/pages/selection/item.go
- truncate command string after copy
- respect log settings
=> fix(ui): UI regressions 

README.md, systemd.md
Add how to run soft-serve using systemd instructions
=> docs: add systemd instructions

cmd/soft/root.go, go.mod, go.sum, internal/log/log.go, internal/sync/workqueue.go, server/config/config.go, server/config/file.go, server/git/git.go, server/jobs.go, server/server.go
=> fix(log): respect log config

go.mod
Soft Serve already uses symbols introduced in go1.20
Fixes: https://github.com/charmbracelet/soft-serve/issues/293
=> feat: bump minimum go version to go1.20

server/backend/utils.go
=> fix: ignore case README filenames

server/cmd/commit.go, server/cmd/repo.go
This PR adds a `repo commit` command that implements #330.
- Installed soft locally
- Started an instance
- Pushed a repo
- Ran the command on a repo
Here's the actual text of the command and its output
```shell
soft-serve on  main [!?] via 🐳 desktop-linux via 🐹 v1.20.3 on ☁️  (us-east-1)
✦ ❯ ssh test repo commit soft 191b8320a037dbb30fa36630b785ff4674c16d64 -c
The authenticity of host '[localhost]:23231 ([::1]:23231)' can't be established.
ED25519 key fingerprint is SHA256:ZEXFXEWF/kZa6MVCMvV65jfyc2GyYabkogseZ3WCxGw.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:23231' (ED25519) to the list of known hosts.
diff --git a/go.mod b/go.mod
index …
```
=> Add commit command

server/git/service.go
Add support to git push options.
Reference: https://git-scm.com/docs/git-push#Documentation/git-push.txt--oltoptiongt
Fixes: https://github.com/charmbracelet/soft-serve/issues/327
=> feat: support git push options

git/attr.go, git/attr_test.go, server/ui/pages/repo/files.go
Check gitattributes for file attrs before displaying files.
Fixes: https://github.com/charmbracelet/soft-serve/issues/238
=> fix: respect gitattributes

server/backend/backend.go, server/backend/repo.go, server/ssh/cmd/import.go, server/task/manager.go
Implement a task manager that can run different tasks given a unique ID.
This is needed to accommodate expensive tasks like importing a large repository. The current behavior uses the connection's context (the SSH connection) to import the repository. However, if the server has defined an SSH `idle_timeout`, `max_timeout`, and/or the connection drops, Soft Serve cancels the git clone process and aborts importing the repository.
Instead, we add the import task to the "task manager" and wait on the connection context. If a task already exists for the same repository, return `Error: import already in progress`.
Fixes: https://github.com/charmbracelet/soft-serve/issues/348
=> feat,fix: add task manager

README.md
- Git LFS support using both HTTP & SSH
- HTTP authentication through user access tokens
- Collaborators' access level
Todo:
=> docs: update readme in preparation of v0.6

go.mod, go.sum, server/ssh/middleware.go
Unauthorized users would get an error message when using commands that need authorization
=> fix: add ssh commands back

server/store/database/settings.go
The keyword "key" is a reserved word in Postgres and must be quoted if used as a column name.
Fixes: https://github.com/charmbracelet/soft-serve/issues/380
=> fix(db): quote postgres keywords

server/ssh/middleware.go, server/ssh/ssh.go
We need to verify that the key used to establish the connection is the same key used for authentication, otherwise, refuse connection.
=> fix(ssh): add authentication middleware

README.md, server/config/config.go, server/config/file.go, server/jobs/jobs.go, server/jobs/mirror.go, server/server.go
Resolves #361 
Initially considered using a map, but this is more explicit which I think is better overall.
=> feat: job config

README.md, go.mod, go.sum, pkg/config/config.go, pkg/db/migrate/0003_migrate_lfs_objects.go, pkg/db/migrate/migrations.go, pkg/git/lfs.go, pkg/git/lfs_log.go, pkg/lfs/pointer.go, pkg/lfs/pointer_test.go
Rename lfs objects from `OID[:2]/OID[2:4]/OID[4:]` to `OID[:2]/OID[2:4]/OID` to follow specs https://github.com/git-lfs/git-lfs/blob/main/docs/spec.md#intercepting-git
=> refactor,fix: add rename lfs objects migration

pkg/git/service.go, pkg/web/context.go, pkg/web/git.go, pkg/web/http.go, pkg/web/logging.go, pkg/web/server.go, pkg/web/util.go
This was due to having a _set_ value of Read/Write http server timeout
values, and a faulty git gzip request handler. The server drops the
connection if there isn't any read/write within 10 seconds.
Replace the read/write timeouts with idle timeout which will reset the
counter to _either_ read/write within 10 seconds. Idle timeout is only
used when keep-alive is enabled. That is the case by default.
Fix git by properly handling gzip and buffered git service responses.
Improve git http handler logging
Fixes: https://github.com/charmbracelet/soft-serve/issues/427
=> fix(http): times out on large repositories

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/lint-soft.yml, .github/workflows/lint.yml
running on both push and pull_request end up running the same job twice for a push on a PR, which waste our CI minutes.
=> build: avoid duplicated CI runs

pkg/config/config.go, pkg/hooks/gen.go
On platforms, where soft-serve executable gets installed in a path that is not the same throughout installation, or upgrades, hooks break. Some examples of such a situation is when moving soft-serve repositories from one OS to another OS, or on NixOS (NixOS/nixpkgs#272128) 
This commit passes the path to the current executable as an environment variable $SOFT_SERVE_EXE_PATH to the hooks.
To fix/update existing repository hooks:
[/path/to/soft-serve/repos] $ grep -ERl \
'^[^[:space:]]+soft-serve[^[:space:]]+' . | xargs sed -r -e \
's,^([^[:space:]]*soft-serve[^[:space:]]*),"${SOFT_SERVE_EXE_PATH}",g' -i
=> fix: executable path in hooks

pkg/backend/collab.go, pkg/proto/errors.go, pkg/webhook/branch_tag.go, pkg/webhook/collaborator.go, pkg/webhook/push.go, pkg/webhook/repository.go, pkg/webhook/webhook.go, testscript/testdata/repo-collab.txtar, testscript/testdata/soft-browse.txtar
Propagate a more informative error when adding an existing collaborator. Ignore webhooks default branch git reference not found errors because the repo won't have a default branch when it's empty.
Fixes: https://github.com/charmbracelet/soft-serve/issues/464
=> fix: invalid error on empty repo collabs

README.md
FIXES 
**ERROR: revision does not exist** 
which occurs since the root.go file has been renamed to main.go and the readme still had command for root.go.
Changes : ~command cmd/soft/root.go~
TO : command cmd/soft/main.go
=> README : changes root.go to main.go

pkg/ssh/cmd/tree.go, pkg/ui/common/format.go, pkg/ui/pages/repo/filesitem.go, testscript/testdata/repo-tree.txtar
Git core.quotePath is enabled by default and causes unicode in filenames to be quoted. Unquote filenames and requote them to escape control characters BUT not unicode characters.
Fixes: https://github.com/charmbracelet/soft-serve/issues/457
=> fix: unquote git quoted filenames

README.md
- Add Windows Install instruction for Winget.
Recently, I added the [manifest](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/charmbracelet/soft-serve) for `soft-serve` to Winget. Once new releases are made, I will update the Winget manifest asap. I have referred to `glow` README for this template.
=> README: add Windows install instruction for Winget

README.md
Made a small adjustment to the make repo private command in README.md as the provided example had elements slightly out of order.
=> Corrected the make repo private example command within the README

README.md
You don't actually need to tap a brew directory before installation. Tapping would happen automatically before installation.
=> docs: Simplify installation with brew

README.md
I only could find the instructions how to create a mirror repo on your blog (https://charm.sh/blog/self-hosted-soft-serve), so I thought it wouldn't hurt to have them also in the README of this nice project :smile:
=> chore(docs): add CLI instructions for mirrors to README

pkg/backend/repo.go
If an LFS client can't be created because it's not compatible for some reason, skip it entirely for a mirrored repo. This prevents one possible crash when mirroring fails. It still seems to crash when accessing user info, so something is still missing. Either way, it seems valid to skip LFS if it just won't work.
Specifically noticed this when trying to import and mirror a repository using a `git@github.com:user/repo` clone URL, which results in the LFS client being nil. It seemed helpful to keep the error as a warning, but otherwise allow mirroring to continue. There might be a better way to handle this, this just lines up more with how the job.mirror code seems to work at the moment.
=> fix(mirror): skip LFS instead of failing to mirror a repo

pkg/backend/repo.go
DeleteRepository, called when mirroring fails, requires access to the user. The user isn't included in the context for the task, so attach the closed over user to the task context.
Noticed this when importing a repo (from #525) and the mirror failed, causing it to try to delete the repo and eventually crash with a segfault accessing user info. The task seems to run with a new context, so hopefully only needed the user attached to the context. In any case, this prevents a segfault now when the changes from #525 aren't also merged.
=> fix(mirror): add user missing from context

docker.md
Hi there :) I've just been playing around with Soft Serve as I've needed to create a new locally hosted instance, and noticed that the Docker documentation was missing the 'SOFT_SERVE_INITIAL_ADMIN_KEYS' environment variable. I've added this to both the Docker and Docker Compose examples in the docker.md.
If this change is not required for any reason, I'm more than happy to adjust or remove the PR. I do however hope this in a small way helps.
=> docs(docker README): Update docker file with SOFT_SERVE_INITIAL_ADMIN_KEYS variable

README.md, pkg/config/config.go, pkg/config/config_test.go, pkg/config/testdata/config.yaml
This PR is related to #553, it simply gives the option to override the config location with the SOFT_SERVE_CONFIG_LOCATION (and checks that a file exists there), otherwise defaults to looking in the config path. Let me know if you have any comments or concerns.
=> feat: optionally pull config from a custom file (envvar), default to data path.

pkg/ssh/cmd/branch.go, testscript/testdata/repo-delete.txtar
This one-line fix addresses a missing constraint error; the `ssh <server> repo branch delete` command can induce a runtime panic when accessing `args[1]` if the the branch was not actually specified as an argument.
Repro steps (note: no branch argument specified)
`ssh soft repo branch delete repofoo`
Output (console on server):
```
2024-07-27 16:23:18 ssh: panic: runtime error: index out of range [0] with length 0
goroutine 934 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/charmbracelet/wish/recover.MiddlewareWithLogger.func2.1.1.1()
/Users/user/go/pkg/mod/github.com/charmbracelet/wish@v1.3.2/recover/recover.go:39 +0x44
panic({0x103990940?, 0x140006946c0?})
/usr/local/go/src/runtime/panic.go:770 +0x124 …
```
=> Add missing arg length check to fix runtime panic

cmd/soft/browse/browse.go, pkg/ssh/ui.go, pkg/ui/components/code/code.go, pkg/ui/pages/repo/log.go, pkg/ui/pages/repo/logitem.go, pkg/ui/pages/repo/refsitem.go, pkg/ui/pages/repo/repo.go, pkg/ui/pages/repo/stash.go
This PR fixes: https://github.com/charmbracelet/soft-serve/issues/540
Ideally, `JoinHorizontal` should expect Top, Bottom, or Center positions. This PR fixes the cases where the Left position constant was used instead of Top.
I found the same thing while looking for `JoinVertical` calls. So I have updated position constants in `JoinVertical` calls as well.
=> fix: update position constant in `JoinHorizontal`

testscript/script_test.go, testscript/testdata/anon-access.txtar, testscript/testdata/help.txtar, testscript/testdata/http.txtar, testscript/testdata/jwt.txtar, testscript/testdata/mirror.txtar, testscript/testdata/repo-blob.txtar, testscript/testdata/repo-collab.txtar, testscript/testdata/repo-commit.txtar, testscript/testdata/repo-create.txtar, testscript/testdata/repo-delete.txtar, testscript/testdata/repo-import.txtar, testscript/testdata/repo-perms.txtar, testscript/testdata/repo-push.txtar, testscript/testdata/repo-tree.txtar, testscript/testdata/repo-webhooks.txtar, testscript/testdata/set-username.txtar, testscript/testdata/settings.txtar, testscript/testdata/ssh-lfs.txtar, testscript/testdata/ssh.txtar, testscript/testdata/token.txtar, testscript/testdata/ui-home.txtar, testscript/testdata/user_management.txtar
The generic "waitforserver" has been renamed to
"ensureserverrunning".
This command now also takes an argument which denotes which environment variable to pick the port from.
This is needed as the ports are randomized by the test.
=> fix: test framework supports ensuring specific port is open

pkg/daemon/daemon.go
This was inconsistent with the other servers.
=> fix: git daemon listens only when starting it

cmd/soft/serve/server.go, pkg/config/config.go, testscript/script_test.go, testscript/testdata/config-servers-git_disabled.txtar, testscript/testdata/config-servers-http_disabled.txtar, testscript/testdata/config-servers-ssh_disabled.txtar, testscript/testdata/config-servers-stats_disabled.txtar
To test this, tests added the new function:
`ensureservernotrunning [SERVICE_NAME]`
(This supersedes the old pull request #600)
closes #594
=> feat: support toggling servers on/off in configuration (#594)

testscript/script_test.go
This is useful on Windows where gcc is not always
available.
=> feat: test framework supports turning off -race flag

pkg/ssh/cmd/branch.go, pkg/ssh/cmd/cmd.go, pkg/ssh/cmd/collab.go, pkg/ssh/cmd/delete.go, pkg/ssh/cmd/description.go, pkg/ssh/cmd/hidden.go, pkg/ssh/cmd/private.go, pkg/ssh/cmd/project_name.go, pkg/ssh/cmd/rename.go, pkg/ssh/cmd/tag.go, testscript/testdata/repo-perms.txtar
This PR fixes the issue by:
- making `checkIfReadable` to return `RepoNotFound` instead of `Unauthorized`
- changing all commands that works on a repo to run `checkIfReadable` before performing anything
- updating tests to reflect the changes
Closes #595
=> fix: prevent enumeration of private repo

pkg/backend/repo.go, pkg/ssh/cmd/cmd.go, pkg/utils/utils.go
This commit fixes a path traversal vulnerability in the repository management code. The `SanitizeRepo` function now correctly returns a sanitized version of the given repository name. It uses an absolute path along with `path.Clean` to ensure that the path is cleaned before being used.
=> fix: prevent path traversal attacks

pkg/ui/pages/repo/repo.go
Previous code only used description width to calculate remaining space.
At that point the description has already been merged into the header so the header can be used to calculate remaining width correctly.
Fixes #521 
E.G.
Before:
After:
=> Fix repo URL width calculation.

README.md, pkg/config/config.go, pkg/config/config_test.go, pkg/web/server.go, testscript/testdata/http-cors.txtar
I needed to clone a soft-serve repo from the browser so I added cors headers.
=> add cors headers

pkg/ui/keymap/keymap.go, pkg/ui/pages/repo/files.go
Minor changes to some help messages, particularly small improvements to the file list view help.
Specifically, code existed to change the help text on the "(c) copy text" key to indicate what would be copied (filename or content), but this code wasn't effecting the change, likely due to copying values into the slice directly instead of pointers. Also, `blame` and line number toggles were being added to the help list, despite those keys having different effects the file list view. Finally, this makes explicit that h and l keys can be used to ascend/descend the file hierarchy in the file list view.
=> fix(ui): help menu on file list view

pkg/web/health.go, pkg/web/server.go
I am running softserve in a k8s cluster and couldn't find an easy way to do liveness and readiness probes. 
I have added the standard k8s healthcheck paths (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) adding a db ping as a prerequisite to readiness, possibly the git server should be added as well? 
I have it running in my clusters from a build of my fork and am happy with this. But figured I would offer the patch upstream if desired. I did not create a discussion for this as i am not sure if this counts as a full "feature." But I can of course create one if desired. 
```bash
➜ k get deploy -n soft-serve soft-serve -oyaml | yq '.spec.template.spec.containers[].image'
ghcr.io/jay-madden/soft-serve:v0.0.1
➜ k get deploy -n soft-serve …
```
=> feat: add readiness and liveness probes for self healing
